class Unit;
int getValue();
void setValue(int val);
void getRow();
void getColumn();
void getSection();
class Row;
Unit *getUnits();
void insert(int position, int value);
bool isValid(int position, int value);
class Column;
Unit *getUnits();
void insert(int position, int value);
bool isValid(int position, int value);
class Section;
Unit *getUnits();
void insert(int position, int value);
bool isValid(int position, int value);
class Sudoku;