class Unit;
int getValue();
void setValue(int val);
int getRow();
int getColumn();
int getSection();
bool getMutability();
class Row;
Unit **getUnits();
void insert(int x, Unit *unit);
bool isValid(int x, int value);
class Column;
Unit **getUnits();
void insert(int y, Unit *unit);
bool isValid(int y, int value);
class Section;
Unit **getUnits();
void insert(int x, int y, Unit *unit);
bool isValid(int x, int y, int value);
class Sudoku;
Row **getRows();
Column **getColumns();
Section **getSections();
Unit **getBoard();
void insert(int x, int y, int value);
bool isValid(int x, int y, int value);
bool isComplete();